name: Willsie2
favicon: null
layout_spectrum: 0.88028
typography_spectrum: 0.6333492966368794
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9972403827123344
  lightness: 0.5412797403987497
  saturation: 0.3812785600312054
  rhythmicContrast: 0.8028140249662101
purpose: []
