analytics: {}
color:
  brandColors:
    - '#D8B0B0'
    - '#081040'
    - '#A86068'
    - '#A81048'
    - '#000000'
  brandStrength: 0.361486
  lightness: 0.717905
  rhythmicContrast: 0.076013
  saturation: 0.261824
cta: {}
layout_spectrum: 0.78161
name: Willsie2
opengraph: {}
purpose: []
typography_spectrum: 0.469594
